(node:12252) DeprecationWarning: Mongoose: mpromise (mongoose's default promise library) is deprecated, plug in your own promise library instead: http://mongoosejs.com/docs/promises.html
Db.prototype.authenticate method will no longer be available in the next major release 3.x as MongoDB 3.6 will only allow auth against users in the admin db and will no longer allow multiple credentials on a socket. Please authenticate using MongoClient.connect with auth credentials.
Db.prototype.authenticate method will no longer be available in the next major release 3.x as MongoDB 3.6 will only allow auth against users in the admin db and will no longer allow multiple credentials on a socket. Please authenticate using MongoClient.connect with auth credentials.
[31merror[39m: uncaughtException: failed to connect to server [localhost:27017] on first connect [MongoError: connection 0 to localhost:27017 timed out] date=Tue Sep 12 2017 11:55:25 GMT-0300 (Hora verano Sudam√©rica Pac√≠fico), pid=5952, uid=null, gid=null, cwd=C:\Users\Daniel\OneDrive\Pega\COMMZGATE\trazability\api, execPath=C:\Program Files\nodejs\node.exe, version=v7.2.0, argv=[C:\Program Files\nodejs\node.exe, C:\Users\Daniel\OneDrive\Pega\COMMZGATE\trazability\api\index.js], rss=66056192, heapTotal=48832512, heapUsed=40106408, external=18060576, loadavg=[0, 0, 0], uptime=236.0505494, trace=[column=35, file=C:\Users\Daniel\OneDrive\Pega\COMMZGATE\trazability\api\node_modules\mongodb-core\lib\topologies\server.js, function=null, line=328, method=null, native=false, column=13, file=events.js, function=emitOne, line=96, method=null, native=false, column=7, file=events.js, function=Pool.emit, line=188, method=emit, native=false, column=12, file=C:\Users\Daniel\OneDrive\Pega\COMMZGATE\trazability\api\node_modules\mongodb-core\lib\connection\pool.js, function=null, line=280, method=null, native=false, column=16, file=events.js, function=Connection.g, line=292, method=g, native=false, column=13, file=events.js, function=emitTwo, line=106, method=null, native=false, column=7, file=events.js, function=Connection.emit, line=191, method=emit, native=false, column=10, file=C:\Users\Daniel\OneDrive\Pega\COMMZGATE\trazability\api\node_modules\mongodb-core\lib\connection\connection.js, function=null, line=187, method=null, native=false, column=16, file=events.js, function=Socket.g, line=292, method=g, native=false, column=13, file=events.js, function=emitNone, line=86, method=null, native=false, column=7, file=events.js, function=Socket.emit, line=185, method=emit, native=false, column=8, file=net.js, function=Socket._onTimeout, line=342, method=_onTimeout, native=false, column=14, file=timers.js, function=ontimeout, line=365, method=null, native=false, column=5, file=timers.js, function=tryOnTimeout, line=237, method=null, native=false, column=5, file=timers.js, function=Timer.listOnTimeout, line=207, method=listOnTimeout, native=false], stack=[MongoError: failed to connect to server [localhost:27017] on first connect [MongoError: connection 0 to localhost:27017 timed out],     at Pool.<anonymous> (C:\Users\Daniel\OneDrive\Pega\COMMZGATE\trazability\api\node_modules\mongodb-core\lib\topologies\server.js:328:35),     at emitOne (events.js:96:13),     at Pool.emit (events.js:188:7),     at Connection.<anonymous> (C:\Users\Daniel\OneDrive\Pega\COMMZGATE\trazability\api\node_modules\mongodb-core\lib\connection\pool.js:280:12),     at Connection.g (events.js:292:16),     at emitTwo (events.js:106:13),     at Connection.emit (events.js:191:7),     at Socket.<anonymous> (C:\Users\Daniel\OneDrive\Pega\COMMZGATE\trazability\api\node_modules\mongodb-core\lib\connection\connection.js:187:10),     at Socket.g (events.js:292:16),     at emitNone (events.js:86:13),     at Socket.emit (events.js:185:7),     at Socket._onTimeout (net.js:342:8),     at ontimeout (timers.js:365:14),     at tryOnTimeout (timers.js:237:5),     at Timer.listOnTimeout (timers.js:207:5)]
Db.prototype.authenticate method will no longer be available in the next major release 3.x as MongoDB 3.6 will only allow auth against users in the admin db and will no longer allow multiple credentials on a socket. Please authenticate using MongoClient.connect with auth credentials.
(node:5952) DeprecationWarning: Mongoose: mpromise (mongoose's default promise library) is deprecated, plug in your own promise library instead: http://mongoosejs.com/docs/promises.html
Db.prototype.authenticate method will no longer be available in the next major release 3.x as MongoDB 3.6 will only allow auth against users in the admin db and will no longer allow multiple credentials on a socket. Please authenticate using MongoClient.connect with auth credentials.
Db.prototype.authenticate method will no longer be available in the next major release 3.x as MongoDB 3.6 will only allow auth against users in the admin db and will no longer allow multiple credentials on a socket. Please authenticate using MongoClient.connect with auth credentials.
(node:5756) DeprecationWarning: Mongoose: mpromise (mongoose's default promise library) is deprecated, plug in your own promise library instead: http://mongoosejs.com/docs/promises.html
Db.prototype.authenticate method will no longer be available in the next major release 3.x as MongoDB 3.6 will only allow auth against users in the admin db and will no longer allow multiple credentials on a socket. Please authenticate using MongoClient.connect with auth credentials.
Db.prototype.authenticate method will no longer be available in the next major release 3.x as MongoDB 3.6 will only allow auth against users in the admin db and will no longer allow multiple credentials on a socket. Please authenticate using MongoClient.connect with auth credentials.
Db.prototype.authenticate method will no longer be available in the next major release 3.x as MongoDB 3.6 will only allow auth against users in the admin db and will no longer allow multiple credentials on a socket. Please authenticate using MongoClient.connect with auth credentials.
Db.prototype.authenticate method will no longer be available in the next major release 3.x as MongoDB 3.6 will only allow auth against users in the admin db and will no longer allow multiple credentials on a socket. Please authenticate using MongoClient.connect with auth credentials.
[31merror[39m: uncaughtException: Ran out of retries trying to reconnect to "localhost:27017". Try setting `server.reconnectTries` and `server.reconnectInterval` to something higher. date=Fri Sep 29 2017 23:22:03 GMT-0300 (Hora verano Sudam√©rica Pac√≠fico), pid=4636, uid=null, gid=null, cwd=C:\Users\Daniel\OneDrive\Pega\COMMZGATE\trazability\api, execPath=C:\Program Files\nodejs\node.exe, version=v7.2.0, argv=[C:\Program Files\nodejs\node.exe, C:\Users\Daniel\OneDrive\Pega\COMMZGATE\trazability\api\index.js], rss=46497792, heapTotal=51978240, heapUsed=42022528, external=17877157, loadavg=[0, 0, 0], uptime=undefined, trace=[column=11, file=C:\Users\Daniel\OneDrive\Pega\COMMZGATE\trazability\api\node_modules\mongoose\lib\error\disconnected.js, function=DisconnectedError, line=21, method=null, native=false, column=31, file=C:\Users\Daniel\OneDrive\Pega\COMMZGATE\trazability\api\node_modules\mongoose\lib\drivers\node-mongodb-native\connection.js, function=null, line=64, method=null, native=false, column=20, file=events.js, function=emitOne, line=101, method=null, native=false, column=7, file=events.js, function=Server.emit, line=188, method=emit, native=false, column=16, file=C:\Users\Daniel\OneDrive\Pega\COMMZGATE\trazability\api\node_modules\mongodb-core\lib\topologies\server.js, function=null, line=319, method=null, native=false, column=13, file=events.js, function=emitOne, line=96, method=null, native=false, column=7, file=events.js, function=Pool.emit, line=188, method=emit, native=false, column=16, file=C:\Users\Daniel\OneDrive\Pega\COMMZGATE\trazability\api\node_modules\mongodb-core\lib\connection\pool.js, function=null, line=317, method=null, native=false, column=13, file=events.js, function=emitTwo, line=106, method=null, native=false, column=7, file=events.js, function=Connection.emit, line=191, method=emit, native=false, column=49, file=C:\Users\Daniel\OneDrive\Pega\COMMZGATE\trazability\api\node_modules\mongodb-core\lib\connection\connection.js, function=null, line=177, method=null, native=false, column=16, file=events.js, function=Socket.g, line=292, method=g, native=false, column=13, file=events.js, function=emitOne, line=96, method=null, native=false, column=7, file=events.js, function=Socket.emit, line=188, method=emit, native=false, column=8, file=net.js, function=connectErrorNT, line=1025, method=null, native=false, column=11, file=internal/process/next_tick.js, function=_combinedTickCallback, line=74, method=null, native=false, column=9, file=internal/process/next_tick.js, function=process._tickCallback, line=98, method=_tickCallback, native=false], stack=[MongooseError: Ran out of retries trying to reconnect to "localhost:27017". Try setting `server.reconnectTries` and `server.reconnectInterval` to something higher.,     at DisconnectedError (C:\Users\Daniel\OneDrive\Pega\COMMZGATE\trazability\api\node_modules\mongoose\lib\error\disconnected.js:21:11),     at Server.<anonymous> (C:\Users\Daniel\OneDrive\Pega\COMMZGATE\trazability\api\node_modules\mongoose\lib\drivers\node-mongodb-native\connection.js:64:31),     at emitOne (events.js:101:20),     at Server.emit (events.js:188:7),     at Pool.<anonymous> (C:\Users\Daniel\OneDrive\Pega\COMMZGATE\trazability\api\node_modules\mongodb-core\lib\topologies\server.js:319:16),     at emitOne (events.js:96:13),     at Pool.emit (events.js:188:7),     at Connection.<anonymous> (C:\Users\Daniel\OneDrive\Pega\COMMZGATE\trazability\api\node_modules\mongodb-core\lib\connection\pool.js:317:16),     at emitTwo (events.js:106:13),     at Connection.emit (events.js:191:7),     at Socket.<anonymous> (C:\Users\Daniel\OneDrive\Pega\COMMZGATE\trazability\api\node_modules\mongodb-core\lib\connection\connection.js:177:49),     at Socket.g (events.js:292:16),     at emitOne (events.js:96:13),     at Socket.emit (events.js:188:7),     at connectErrorNT (net.js:1025:8),     at _combinedTickCallback (internal/process/next_tick.js:74:11),     at process._tickCallback (internal/process/next_tick.js:98:9)]
[31merror[39m: uncaughtException: Ran out of retries trying to reconnect to "localhost:27017". Try setting `server.reconnectTries` and `server.reconnectInterval` to something higher. date=Fri Sep 29 2017 23:22:04 GMT-0300 (Hora verano Sudam√©rica Pac√≠fico), pid=4636, uid=null, gid=null, cwd=C:\Users\Daniel\OneDrive\Pega\COMMZGATE\trazability\api, execPath=C:\Program Files\nodejs\node.exe, version=v7.2.0, argv=[C:\Program Files\nodejs\node.exe, C:\Users\Daniel\OneDrive\Pega\COMMZGATE\trazability\api\index.js], rss=47026176, heapTotal=51978240, heapUsed=41699400, external=17881645, loadavg=[0, 0, 0], uptime=undefined, trace=[column=11, file=C:\Users\Daniel\OneDrive\Pega\COMMZGATE\trazability\api\node_modules\mongoose\lib\error\disconnected.js, function=DisconnectedError, line=21, method=null, native=false, column=31, file=C:\Users\Daniel\OneDrive\Pega\COMMZGATE\trazability\api\node_modules\mongoose\lib\drivers\node-mongodb-native\connection.js, function=null, line=64, method=null, native=false, column=20, file=events.js, function=emitOne, line=101, method=null, native=false, column=7, file=events.js, function=Server.emit, line=188, method=emit, native=false, column=16, file=C:\Users\Daniel\OneDrive\Pega\COMMZGATE\trazability\api\node_modules\mongodb-core\lib\topologies\server.js, function=null, line=319, method=null, native=false, column=13, file=events.js, function=emitOne, line=96, method=null, native=false, column=7, file=events.js, function=Pool.emit, line=188, method=emit, native=false, column=16, file=C:\Users\Daniel\OneDrive\Pega\COMMZGATE\trazability\api\node_modules\mongodb-core\lib\connection\pool.js, function=null, line=317, method=null, native=false, column=13, file=events.js, function=emitTwo, line=106, method=null, native=false, column=7, file=events.js, function=Connection.emit, line=191, method=emit, native=false, column=49, file=C:\Users\Daniel\OneDrive\Pega\COMMZGATE\trazability\api\node_modules\mongodb-core\lib\connection\connection.js, function=null, line=177, method=null, native=false, column=16, file=events.js, function=Socket.g, line=292, method=g, native=false, column=13, file=events.js, function=emitOne, line=96, method=null, native=false, column=7, file=events.js, function=Socket.emit, line=188, method=emit, native=false, column=8, file=net.js, function=connectErrorNT, line=1025, method=null, native=false, column=11, file=internal/process/next_tick.js, function=_combinedTickCallback, line=74, method=null, native=false, column=9, file=internal/process/next_tick.js, function=process._tickCallback, line=98, method=_tickCallback, native=false], stack=[MongooseError: Ran out of retries trying to reconnect to "localhost:27017". Try setting `server.reconnectTries` and `server.reconnectInterval` to something higher.,     at DisconnectedError (C:\Users\Daniel\OneDrive\Pega\COMMZGATE\trazability\api\node_modules\mongoose\lib\error\disconnected.js:21:11),     at Server.<anonymous> (C:\Users\Daniel\OneDrive\Pega\COMMZGATE\trazability\api\node_modules\mongoose\lib\drivers\node-mongodb-native\connection.js:64:31),     at emitOne (events.js:101:20),     at Server.emit (events.js:188:7),     at Pool.<anonymous> (C:\Users\Daniel\OneDrive\Pega\COMMZGATE\trazability\api\node_modules\mongodb-core\lib\topologies\server.js:319:16),     at emitOne (events.js:96:13),     at Pool.emit (events.js:188:7),     at Connection.<anonymous> (C:\Users\Daniel\OneDrive\Pega\COMMZGATE\trazability\api\node_modules\mongodb-core\lib\connection\pool.js:317:16),     at emitTwo (events.js:106:13),     at Connection.emit (events.js:191:7),     at Socket.<anonymous> (C:\Users\Daniel\OneDrive\Pega\COMMZGATE\trazability\api\node_modules\mongodb-core\lib\connection\connection.js:177:49),     at Socket.g (events.js:292:16),     at emitOne (events.js:96:13),     at Socket.emit (events.js:188:7),     at connectErrorNT (net.js:1025:8),     at _combinedTickCallback (internal/process/next_tick.js:74:11),     at process._tickCallback (internal/process/next_tick.js:98:9)]
Db.prototype.authenticate method will no longer be available in the next major release 3.x as MongoDB 3.6 will only allow auth against users in the admin db and will no longer allow multiple credentials on a socket. Please authenticate using MongoClient.connect with auth credentials.
Db.prototype.authenticate method will no longer be available in the next major release 3.x as MongoDB 3.6 will only allow auth against users in the admin db and will no longer allow multiple credentials on a socket. Please authenticate using MongoClient.connect with auth credentials.
Db.prototype.authenticate method will no longer be available in the next major release 3.x as MongoDB 3.6 will only allow auth against users in the admin db and will no longer allow multiple credentials on a socket. Please authenticate using MongoClient.connect with auth credentials.
Db.prototype.authenticate method will no longer be available in the next major release 3.x as MongoDB 3.6 will only allow auth against users in the admin db and will no longer allow multiple credentials on a socket. Please authenticate using MongoClient.connect with auth credentials.
Db.prototype.authenticate method will no longer be available in the next major release 3.x as MongoDB 3.6 will only allow auth against users in the admin db and will no longer allow multiple credentials on a socket. Please authenticate using MongoClient.connect with auth credentials.
Db.prototype.authenticate method will no longer be available in the next major release 3.x as MongoDB 3.6 will only allow auth against users in the admin db and will no longer allow multiple credentials on a socket. Please authenticate using MongoClient.connect with auth credentials.
(node:6108) DeprecationWarning: Mongoose: mpromise (mongoose's default promise library) is deprecated, plug in your own promise library instead: http://mongoosejs.com/docs/promises.html
[31merror[39m: uncaughtException: Cannot read property 'geometry' of undefined date=Mon Oct 02 2017 12:53:56 GMT-0300 (Hora verano Sudam√©rica Pac√≠fico), pid=6108, uid=null, gid=null, cwd=C:\Users\Daniel\OneDrive\Pega\COMMZGATE\trazability\api, execPath=C:\Program Files\nodejs\node.exe, version=v7.2.0, argv=[C:\Program Files\nodejs\node.exe, C:\Users\Daniel\OneDrive\Pega\COMMZGATE\trazability\api\index.js], rss=46256128, heapTotal=55123968, heapUsed=46239936, external=18187208, loadavg=[0, 0, 0], uptime=64359.0865707, trace=[column=39, file=C:\Users\Daniel\OneDrive\Pega\COMMZGATE\trazability\api\middlewares\geocoding.js, function=Request._callback, line=20, method=_callback, native=false, column=22, file=C:\Users\Daniel\OneDrive\Pega\COMMZGATE\trazability\api\node_modules\request\request.js, function=Request.self.callback, line=186, method=callback, native=false, column=13, file=events.js, function=emitTwo, line=106, method=null, native=false, column=7, file=events.js, function=Request.emit, line=191, method=emit, native=false, column=10, file=C:\Users\Daniel\OneDrive\Pega\COMMZGATE\trazability\api\node_modules\request\request.js, function=null, line=1163, method=null, native=false, column=13, file=events.js, function=emitOne, line=96, method=null, native=false, column=7, file=events.js, function=Request.emit, line=188, method=emit, native=false, column=12, file=C:\Users\Daniel\OneDrive\Pega\COMMZGATE\trazability\api\node_modules\request\request.js, function=null, line=1085, method=null, native=false, column=16, file=events.js, function=IncomingMessage.g, line=292, method=g, native=false, column=20, file=events.js, function=emitNone, line=91, method=null, native=false, column=7, file=events.js, function=IncomingMessage.emit, line=185, method=emit, native=false, column=12, file=_stream_readable.js, function=endReadableNT, line=974, method=null, native=false, column=11, file=internal/process/next_tick.js, function=_combinedTickCallback, line=74, method=null, native=false, column=9, file=internal/process/next_tick.js, function=process._tickCallback, line=98, method=_tickCallback, native=false], stack=[TypeError: Cannot read property 'geometry' of undefined,     at Request._callback (C:\Users\Daniel\OneDrive\Pega\COMMZGATE\trazability\api\middlewares\geocoding.js:20:39),     at Request.self.callback (C:\Users\Daniel\OneDrive\Pega\COMMZGATE\trazability\api\node_modules\request\request.js:186:22),     at emitTwo (events.js:106:13),     at Request.emit (events.js:191:7),     at Request.<anonymous> (C:\Users\Daniel\OneDrive\Pega\COMMZGATE\trazability\api\node_modules\request\request.js:1163:10),     at emitOne (events.js:96:13),     at Request.emit (events.js:188:7),     at IncomingMessage.<anonymous> (C:\Users\Daniel\OneDrive\Pega\COMMZGATE\trazability\api\node_modules\request\request.js:1085:12),     at IncomingMessage.g (events.js:292:16),     at emitNone (events.js:91:20),     at IncomingMessage.emit (events.js:185:7),     at endReadableNT (_stream_readable.js:974:12),     at _combinedTickCallback (internal/process/next_tick.js:74:11),     at process._tickCallback (internal/process/next_tick.js:98:9)]
[31merror[39m: uncaughtException: failed to connect to server [localhost:27017] on first connect [MongoError: connection 0 to localhost:27017 timed out] date=Wed Oct 11 2017 09:54:18 GMT-0300 (Hora verano Sudam√©rica Pac√≠fico), pid=6040, uid=null, gid=null, cwd=C:\Users\Daniel\OneDrive\Pega\COMMZGATE\trazability\api, execPath=C:\Program Files\nodejs\node.exe, version=v7.2.0, argv=[C:\Program Files\nodejs\node.exe, C:\Users\Daniel\OneDrive\Pega\COMMZGATE\trazability\api\index.js], rss=70303744, heapTotal=57221120, heapUsed=43923080, external=18148000, loadavg=[0, 0, 0], uptime=519.6047362, trace=[column=35, file=C:\Users\Daniel\OneDrive\Pega\COMMZGATE\trazability\api\node_modules\mongodb-core\lib\topologies\server.js, function=null, line=328, method=null, native=false, column=13, file=events.js, function=emitOne, line=96, method=null, native=false, column=7, file=events.js, function=Pool.emit, line=188, method=emit, native=false, column=12, file=C:\Users\Daniel\OneDrive\Pega\COMMZGATE\trazability\api\node_modules\mongodb-core\lib\connection\pool.js, function=null, line=280, method=null, native=false, column=16, file=events.js, function=Connection.g, line=292, method=g, native=false, column=13, file=events.js, function=emitTwo, line=106, method=null, native=false, column=7, file=events.js, function=Connection.emit, line=191, method=emit, native=false, column=10, file=C:\Users\Daniel\OneDrive\Pega\COMMZGATE\trazability\api\node_modules\mongodb-core\lib\connection\connection.js, function=null, line=187, method=null, native=false, column=16, file=events.js, function=Socket.g, line=292, method=g, native=false, column=13, file=events.js, function=emitNone, line=86, method=null, native=false, column=7, file=events.js, function=Socket.emit, line=185, method=emit, native=false, column=8, file=net.js, function=Socket._onTimeout, line=342, method=_onTimeout, native=false, column=14, file=timers.js, function=ontimeout, line=365, method=null, native=false, column=5, file=timers.js, function=tryOnTimeout, line=237, method=null, native=false, column=5, file=timers.js, function=Timer.listOnTimeout, line=207, method=listOnTimeout, native=false], stack=[MongoError: failed to connect to server [localhost:27017] on first connect [MongoError: connection 0 to localhost:27017 timed out],     at Pool.<anonymous> (C:\Users\Daniel\OneDrive\Pega\COMMZGATE\trazability\api\node_modules\mongodb-core\lib\topologies\server.js:328:35),     at emitOne (events.js:96:13),     at Pool.emit (events.js:188:7),     at Connection.<anonymous> (C:\Users\Daniel\OneDrive\Pega\COMMZGATE\trazability\api\node_modules\mongodb-core\lib\connection\pool.js:280:12),     at Connection.g (events.js:292:16),     at emitTwo (events.js:106:13),     at Connection.emit (events.js:191:7),     at Socket.<anonymous> (C:\Users\Daniel\OneDrive\Pega\COMMZGATE\trazability\api\node_modules\mongodb-core\lib\connection\connection.js:187:10),     at Socket.g (events.js:292:16),     at emitNone (events.js:86:13),     at Socket.emit (events.js:185:7),     at Socket._onTimeout (net.js:342:8),     at ontimeout (timers.js:365:14),     at tryOnTimeout (timers.js:237:5),     at Timer.listOnTimeout (timers.js:207:5)]
Db.prototype.authenticate method will no longer be available in the next major release 3.x as MongoDB 3.6 will only allow auth against users in the admin db and will no longer allow multiple credentials on a socket. Please authenticate using MongoClient.connect with auth credentials.
[31merror[39m: uncaughtException: failed to connect to server [localhost:27017] on first connect [MongoError: connection 0 to localhost:27017 timed out] date=Sat Oct 14 2017 22:00:38 GMT-0300 (Hora verano Sudam√©rica Pac√≠fico), pid=3752, uid=null, gid=null, cwd=C:\Users\Daniel\OneDrive\Pega\COMMZGATE\trazability\api, execPath=C:\Program Files\nodejs\node.exe, version=v7.2.0, argv=[C:\Program Files\nodejs\node.exe, C:\Users\Daniel\OneDrive\Pega\COMMZGATE\trazability\api\index.js], rss=71135232, heapTotal=55123968, heapUsed=44412576, external=18068768, loadavg=[0, 0, 0], uptime=669.7084128, trace=[column=35, file=C:\Users\Daniel\OneDrive\Pega\COMMZGATE\trazability\api\node_modules\mongodb-core\lib\topologies\server.js, function=null, line=328, method=null, native=false, column=13, file=events.js, function=emitOne, line=96, method=null, native=false, column=7, file=events.js, function=Pool.emit, line=188, method=emit, native=false, column=12, file=C:\Users\Daniel\OneDrive\Pega\COMMZGATE\trazability\api\node_modules\mongodb-core\lib\connection\pool.js, function=null, line=280, method=null, native=false, column=16, file=events.js, function=Connection.g, line=292, method=g, native=false, column=13, file=events.js, function=emitTwo, line=106, method=null, native=false, column=7, file=events.js, function=Connection.emit, line=191, method=emit, native=false, column=10, file=C:\Users\Daniel\OneDrive\Pega\COMMZGATE\trazability\api\node_modules\mongodb-core\lib\connection\connection.js, function=null, line=187, method=null, native=false, column=16, file=events.js, function=Socket.g, line=292, method=g, native=false, column=13, file=events.js, function=emitNone, line=86, method=null, native=false, column=7, file=events.js, function=Socket.emit, line=185, method=emit, native=false, column=8, file=net.js, function=Socket._onTimeout, line=342, method=_onTimeout, native=false, column=14, file=timers.js, function=ontimeout, line=365, method=null, native=false, column=5, file=timers.js, function=tryOnTimeout, line=237, method=null, native=false, column=5, file=timers.js, function=Timer.listOnTimeout, line=207, method=listOnTimeout, native=false], stack=[MongoError: failed to connect to server [localhost:27017] on first connect [MongoError: connection 0 to localhost:27017 timed out],     at Pool.<anonymous> (C:\Users\Daniel\OneDrive\Pega\COMMZGATE\trazability\api\node_modules\mongodb-core\lib\topologies\server.js:328:35),     at emitOne (events.js:96:13),     at Pool.emit (events.js:188:7),     at Connection.<anonymous> (C:\Users\Daniel\OneDrive\Pega\COMMZGATE\trazability\api\node_modules\mongodb-core\lib\connection\pool.js:280:12),     at Connection.g (events.js:292:16),     at emitTwo (events.js:106:13),     at Connection.emit (events.js:191:7),     at Socket.<anonymous> (C:\Users\Daniel\OneDrive\Pega\COMMZGATE\trazability\api\node_modules\mongodb-core\lib\connection\connection.js:187:10),     at Socket.g (events.js:292:16),     at emitNone (events.js:86:13),     at Socket.emit (events.js:185:7),     at Socket._onTimeout (net.js:342:8),     at ontimeout (timers.js:365:14),     at tryOnTimeout (timers.js:237:5),     at Timer.listOnTimeout (timers.js:207:5)]
Db.prototype.authenticate method will no longer be available in the next major release 3.x as MongoDB 3.6 will only allow auth against users in the admin db and will no longer allow multiple credentials on a socket. Please authenticate using MongoClient.connect with auth credentials.
[31merror[39m: uncaughtException: failed to connect to server [localhost:27017] on first connect [MongoError: connection 0 to localhost:27017 timed out] date=Sun Oct 15 2017 16:02:58 GMT-0300 (Hora verano Sudam√©rica Pac√≠fico), pid=6092, uid=null, gid=null, cwd=C:\Users\Daniel\OneDrive\Pega\COMMZGATE\trazability\api, execPath=C:\Program Files\nodejs\node.exe, version=v7.2.0, argv=[C:\Program Files\nodejs\node.exe, C:\Users\Daniel\OneDrive\Pega\COMMZGATE\trazability\api\index.js], rss=72491008, heapTotal=63512576, heapUsed=44321152, external=18061669, loadavg=[0, 0, 0], uptime=5025.7791856, trace=[column=35, file=C:\Users\Daniel\OneDrive\Pega\COMMZGATE\trazability\api\node_modules\mongodb-core\lib\topologies\server.js, function=null, line=328, method=null, native=false, column=13, file=events.js, function=emitOne, line=96, method=null, native=false, column=7, file=events.js, function=Pool.emit, line=188, method=emit, native=false, column=12, file=C:\Users\Daniel\OneDrive\Pega\COMMZGATE\trazability\api\node_modules\mongodb-core\lib\connection\pool.js, function=null, line=280, method=null, native=false, column=16, file=events.js, function=Connection.g, line=292, method=g, native=false, column=13, file=events.js, function=emitTwo, line=106, method=null, native=false, column=7, file=events.js, function=Connection.emit, line=191, method=emit, native=false, column=10, file=C:\Users\Daniel\OneDrive\Pega\COMMZGATE\trazability\api\node_modules\mongodb-core\lib\connection\connection.js, function=null, line=187, method=null, native=false, column=16, file=events.js, function=Socket.g, line=292, method=g, native=false, column=13, file=events.js, function=emitNone, line=86, method=null, native=false, column=7, file=events.js, function=Socket.emit, line=185, method=emit, native=false, column=8, file=net.js, function=Socket._onTimeout, line=342, method=_onTimeout, native=false, column=14, file=timers.js, function=ontimeout, line=365, method=null, native=false, column=5, file=timers.js, function=tryOnTimeout, line=237, method=null, native=false, column=5, file=timers.js, function=Timer.listOnTimeout, line=207, method=listOnTimeout, native=false], stack=[MongoError: failed to connect to server [localhost:27017] on first connect [MongoError: connection 0 to localhost:27017 timed out],     at Pool.<anonymous> (C:\Users\Daniel\OneDrive\Pega\COMMZGATE\trazability\api\node_modules\mongodb-core\lib\topologies\server.js:328:35),     at emitOne (events.js:96:13),     at Pool.emit (events.js:188:7),     at Connection.<anonymous> (C:\Users\Daniel\OneDrive\Pega\COMMZGATE\trazability\api\node_modules\mongodb-core\lib\connection\pool.js:280:12),     at Connection.g (events.js:292:16),     at emitTwo (events.js:106:13),     at Connection.emit (events.js:191:7),     at Socket.<anonymous> (C:\Users\Daniel\OneDrive\Pega\COMMZGATE\trazability\api\node_modules\mongodb-core\lib\connection\connection.js:187:10),     at Socket.g (events.js:292:16),     at emitNone (events.js:86:13),     at Socket.emit (events.js:185:7),     at Socket._onTimeout (net.js:342:8),     at ontimeout (timers.js:365:14),     at tryOnTimeout (timers.js:237:5),     at Timer.listOnTimeout (timers.js:207:5)]
Db.prototype.authenticate method will no longer be available in the next major release 3.x as MongoDB 3.6 will only allow auth against users in the admin db and will no longer allow multiple credentials on a socket. Please authenticate using MongoClient.connect with auth credentials.
[31merror[39m: uncaughtException: failed to connect to server [localhost:27017] on first connect [MongoError: connection 0 to localhost:27017 timed out] date=Mon Oct 16 2017 09:22:54 GMT-0300 (Hora verano Sudam√©rica Pac√≠fico), pid=1420, uid=null, gid=null, cwd=C:\Users\Daniel\OneDrive\Pega\COMMZGATE\trazability\api, execPath=C:\Program Files\nodejs\node.exe, version=v7.2.0, argv=[C:\Program Files\nodejs\node.exe, C:\Users\Daniel\OneDrive\Pega\COMMZGATE\trazability\api\index.js], rss=73506816, heapTotal=56172544, heapUsed=43481192, external=17891868, loadavg=[0, 0, 0], uptime=421.9964543, trace=[column=35, file=C:\Users\Daniel\OneDrive\Pega\COMMZGATE\trazability\api\node_modules\mongodb-core\lib\topologies\server.js, function=null, line=328, method=null, native=false, column=13, file=events.js, function=emitOne, line=96, method=null, native=false, column=7, file=events.js, function=Pool.emit, line=188, method=emit, native=false, column=12, file=C:\Users\Daniel\OneDrive\Pega\COMMZGATE\trazability\api\node_modules\mongodb-core\lib\connection\pool.js, function=null, line=280, method=null, native=false, column=16, file=events.js, function=Connection.g, line=292, method=g, native=false, column=13, file=events.js, function=emitTwo, line=106, method=null, native=false, column=7, file=events.js, function=Connection.emit, line=191, method=emit, native=false, column=10, file=C:\Users\Daniel\OneDrive\Pega\COMMZGATE\trazability\api\node_modules\mongodb-core\lib\connection\connection.js, function=null, line=187, method=null, native=false, column=16, file=events.js, function=Socket.g, line=292, method=g, native=false, column=13, file=events.js, function=emitNone, line=86, method=null, native=false, column=7, file=events.js, function=Socket.emit, line=185, method=emit, native=false, column=8, file=net.js, function=Socket._onTimeout, line=342, method=_onTimeout, native=false, column=14, file=timers.js, function=ontimeout, line=365, method=null, native=false, column=5, file=timers.js, function=tryOnTimeout, line=237, method=null, native=false, column=5, file=timers.js, function=Timer.listOnTimeout, line=207, method=listOnTimeout, native=false], stack=[MongoError: failed to connect to server [localhost:27017] on first connect [MongoError: connection 0 to localhost:27017 timed out],     at Pool.<anonymous> (C:\Users\Daniel\OneDrive\Pega\COMMZGATE\trazability\api\node_modules\mongodb-core\lib\topologies\server.js:328:35),     at emitOne (events.js:96:13),     at Pool.emit (events.js:188:7),     at Connection.<anonymous> (C:\Users\Daniel\OneDrive\Pega\COMMZGATE\trazability\api\node_modules\mongodb-core\lib\connection\pool.js:280:12),     at Connection.g (events.js:292:16),     at emitTwo (events.js:106:13),     at Connection.emit (events.js:191:7),     at Socket.<anonymous> (C:\Users\Daniel\OneDrive\Pega\COMMZGATE\trazability\api\node_modules\mongodb-core\lib\connection\connection.js:187:10),     at Socket.g (events.js:292:16),     at emitNone (events.js:86:13),     at Socket.emit (events.js:185:7),     at Socket._onTimeout (net.js:342:8),     at ontimeout (timers.js:365:14),     at tryOnTimeout (timers.js:237:5),     at Timer.listOnTimeout (timers.js:207:5)]
Db.prototype.authenticate method will no longer be available in the next major release 3.x as MongoDB 3.6 will only allow auth against users in the admin db and will no longer allow multiple credentials on a socket. Please authenticate using MongoClient.connect with auth credentials.
(node:1420) DeprecationWarning: Mongoose: mpromise (mongoose's default promise library) is deprecated, plug in your own promise library instead: http://mongoosejs.com/docs/promises.html
[31merror[39m: uncaughtException: failed to connect to server [localhost:27017] on first connect [MongoError: connection 0 to localhost:27017 timed out] date=Fri Oct 20 2017 10:51:59 GMT-0300 (Hora verano Sudam√©rica Pac√≠fico), pid=4988, uid=null, gid=null, cwd=C:\Users\Daniel\OneDrive\Pega\COMMZGATE\trazability\api, execPath=C:\Program Files\nodejs\node.exe, version=v7.2.0, argv=[C:\Program Files\nodejs\node.exe, C:\Users\Daniel\OneDrive\Pega\COMMZGATE\trazability\api\index.js], rss=70053888, heapTotal=56172544, heapUsed=44757408, external=18110821, loadavg=[0, 0, 0], uptime=354.3765704, trace=[column=35, file=C:\Users\Daniel\OneDrive\Pega\COMMZGATE\trazability\api\node_modules\mongodb-core\lib\topologies\server.js, function=null, line=328, method=null, native=false, column=13, file=events.js, function=emitOne, line=96, method=null, native=false, column=7, file=events.js, function=Pool.emit, line=188, method=emit, native=false, column=12, file=C:\Users\Daniel\OneDrive\Pega\COMMZGATE\trazability\api\node_modules\mongodb-core\lib\connection\pool.js, function=null, line=280, method=null, native=false, column=16, file=events.js, function=Connection.g, line=292, method=g, native=false, column=13, file=events.js, function=emitTwo, line=106, method=null, native=false, column=7, file=events.js, function=Connection.emit, line=191, method=emit, native=false, column=10, file=C:\Users\Daniel\OneDrive\Pega\COMMZGATE\trazability\api\node_modules\mongodb-core\lib\connection\connection.js, function=null, line=187, method=null, native=false, column=16, file=events.js, function=Socket.g, line=292, method=g, native=false, column=13, file=events.js, function=emitNone, line=86, method=null, native=false, column=7, file=events.js, function=Socket.emit, line=185, method=emit, native=false, column=8, file=net.js, function=Socket._onTimeout, line=342, method=_onTimeout, native=false, column=14, file=timers.js, function=ontimeout, line=365, method=null, native=false, column=5, file=timers.js, function=tryOnTimeout, line=237, method=null, native=false, column=5, file=timers.js, function=Timer.listOnTimeout, line=207, method=listOnTimeout, native=false], stack=[MongoError: failed to connect to server [localhost:27017] on first connect [MongoError: connection 0 to localhost:27017 timed out],     at Pool.<anonymous> (C:\Users\Daniel\OneDrive\Pega\COMMZGATE\trazability\api\node_modules\mongodb-core\lib\topologies\server.js:328:35),     at emitOne (events.js:96:13),     at Pool.emit (events.js:188:7),     at Connection.<anonymous> (C:\Users\Daniel\OneDrive\Pega\COMMZGATE\trazability\api\node_modules\mongodb-core\lib\connection\pool.js:280:12),     at Connection.g (events.js:292:16),     at emitTwo (events.js:106:13),     at Connection.emit (events.js:191:7),     at Socket.<anonymous> (C:\Users\Daniel\OneDrive\Pega\COMMZGATE\trazability\api\node_modules\mongodb-core\lib\connection\connection.js:187:10),     at Socket.g (events.js:292:16),     at emitNone (events.js:86:13),     at Socket.emit (events.js:185:7),     at Socket._onTimeout (net.js:342:8),     at ontimeout (timers.js:365:14),     at tryOnTimeout (timers.js:237:5),     at Timer.listOnTimeout (timers.js:207:5)]
Db.prototype.authenticate method will no longer be available in the next major release 3.x as MongoDB 3.6 will only allow auth against users in the admin db and will no longer allow multiple credentials on a socket. Please authenticate using MongoClient.connect with auth credentials.
Db.prototype.authenticate method will no longer be available in the next major release 3.x as MongoDB 3.6 will only allow auth against users in the admin db and will no longer allow multiple credentials on a socket. Please authenticate using MongoClient.connect with auth credentials.
Db.prototype.authenticate method will no longer be available in the next major release 3.x as MongoDB 3.6 will only allow auth against users in the admin db and will no longer allow multiple credentials on a socket. Please authenticate using MongoClient.connect with auth credentials.
Db.prototype.authenticate method will no longer be available in the next major release 3.x as MongoDB 3.6 will only allow auth against users in the admin db and will no longer allow multiple credentials on a socket. Please authenticate using MongoClient.connect with auth credentials.
Db.prototype.authenticate method will no longer be available in the next major release 3.x as MongoDB 3.6 will only allow auth against users in the admin db and will no longer allow multiple credentials on a socket. Please authenticate using MongoClient.connect with auth credentials.
[31merror[39m: uncaughtException: failed to connect to server [localhost:27017] on first connect [MongoError: connection 0 to localhost:27017 timed out] date=Mon Oct 23 2017 10:42:40 GMT-0300 (Hora verano Sudam√©rica Pac√≠fico), pid=6296, uid=null, gid=null, cwd=C:\Users\Daniel\OneDrive\Pega\COMMZGATE\trazability\api, execPath=C:\Program Files\nodejs\node.exe, version=v7.2.0, argv=[C:\Program Files\nodejs\node.exe, C:\Users\Daniel\OneDrive\Pega\COMMZGATE\trazability\api\index.js], rss=73601024, heapTotal=56172544, heapUsed=44499632, external=18060576, loadavg=[0, 0, 0], uptime=367.2346012, trace=[column=35, file=C:\Users\Daniel\OneDrive\Pega\COMMZGATE\trazability\api\node_modules\mongodb-core\lib\topologies\server.js, function=null, line=328, method=null, native=false, column=13, file=events.js, function=emitOne, line=96, method=null, native=false, column=7, file=events.js, function=Pool.emit, line=188, method=emit, native=false, column=12, file=C:\Users\Daniel\OneDrive\Pega\COMMZGATE\trazability\api\node_modules\mongodb-core\lib\connection\pool.js, function=null, line=280, method=null, native=false, column=16, file=events.js, function=Connection.g, line=292, method=g, native=false, column=13, file=events.js, function=emitTwo, line=106, method=null, native=false, column=7, file=events.js, function=Connection.emit, line=191, method=emit, native=false, column=10, file=C:\Users\Daniel\OneDrive\Pega\COMMZGATE\trazability\api\node_modules\mongodb-core\lib\connection\connection.js, function=null, line=187, method=null, native=false, column=16, file=events.js, function=Socket.g, line=292, method=g, native=false, column=13, file=events.js, function=emitNone, line=86, method=null, native=false, column=7, file=events.js, function=Socket.emit, line=185, method=emit, native=false, column=8, file=net.js, function=Socket._onTimeout, line=342, method=_onTimeout, native=false, column=14, file=timers.js, function=ontimeout, line=365, method=null, native=false, column=5, file=timers.js, function=tryOnTimeout, line=237, method=null, native=false, column=5, file=timers.js, function=Timer.listOnTimeout, line=207, method=listOnTimeout, native=false], stack=[MongoError: failed to connect to server [localhost:27017] on first connect [MongoError: connection 0 to localhost:27017 timed out],     at Pool.<anonymous> (C:\Users\Daniel\OneDrive\Pega\COMMZGATE\trazability\api\node_modules\mongodb-core\lib\topologies\server.js:328:35),     at emitOne (events.js:96:13),     at Pool.emit (events.js:188:7),     at Connection.<anonymous> (C:\Users\Daniel\OneDrive\Pega\COMMZGATE\trazability\api\node_modules\mongodb-core\lib\connection\pool.js:280:12),     at Connection.g (events.js:292:16),     at emitTwo (events.js:106:13),     at Connection.emit (events.js:191:7),     at Socket.<anonymous> (C:\Users\Daniel\OneDrive\Pega\COMMZGATE\trazability\api\node_modules\mongodb-core\lib\connection\connection.js:187:10),     at Socket.g (events.js:292:16),     at emitNone (events.js:86:13),     at Socket.emit (events.js:185:7),     at Socket._onTimeout (net.js:342:8),     at ontimeout (timers.js:365:14),     at tryOnTimeout (timers.js:237:5),     at Timer.listOnTimeout (timers.js:207:5)]
Db.prototype.authenticate method will no longer be available in the next major release 3.x as MongoDB 3.6 will only allow auth against users in the admin db and will no longer allow multiple credentials on a socket. Please authenticate using MongoClient.connect with auth credentials.
[31merror[39m: uncaughtException: failed to connect to server [localhost:27017] on first connect [MongoError: connection 0 to localhost:27017 timed out] date=Thu Oct 26 2017 09:21:27 GMT-0300 (Hora verano Sudam√©rica Pac√≠fico), pid=6264, uid=null, gid=null, cwd=C:\Users\Daniel\OneDrive\Pega\COMMZGATE\trazability\api, execPath=C:\Program Files\nodejs\node.exe, version=v7.2.0, argv=[C:\Program Files\nodejs\node.exe, C:\Users\Daniel\OneDrive\Pega\COMMZGATE\trazability\api\index.js], rss=71704576, heapTotal=55123968, heapUsed=44123008, external=17929504, loadavg=[0, 0, 0], uptime=432.0020467, trace=[column=35, file=C:\Users\Daniel\OneDrive\Pega\COMMZGATE\trazability\api\node_modules\mongodb-core\lib\topologies\server.js, function=null, line=328, method=null, native=false, column=13, file=events.js, function=emitOne, line=96, method=null, native=false, column=7, file=events.js, function=Pool.emit, line=188, method=emit, native=false, column=12, file=C:\Users\Daniel\OneDrive\Pega\COMMZGATE\trazability\api\node_modules\mongodb-core\lib\connection\pool.js, function=null, line=280, method=null, native=false, column=16, file=events.js, function=Connection.g, line=292, method=g, native=false, column=13, file=events.js, function=emitTwo, line=106, method=null, native=false, column=7, file=events.js, function=Connection.emit, line=191, method=emit, native=false, column=10, file=C:\Users\Daniel\OneDrive\Pega\COMMZGATE\trazability\api\node_modules\mongodb-core\lib\connection\connection.js, function=null, line=187, method=null, native=false, column=16, file=events.js, function=Socket.g, line=292, method=g, native=false, column=13, file=events.js, function=emitNone, line=86, method=null, native=false, column=7, file=events.js, function=Socket.emit, line=185, method=emit, native=false, column=8, file=net.js, function=Socket._onTimeout, line=342, method=_onTimeout, native=false, column=14, file=timers.js, function=ontimeout, line=365, method=null, native=false, column=5, file=timers.js, function=tryOnTimeout, line=237, method=null, native=false, column=5, file=timers.js, function=Timer.listOnTimeout, line=207, method=listOnTimeout, native=false], stack=[MongoError: failed to connect to server [localhost:27017] on first connect [MongoError: connection 0 to localhost:27017 timed out],     at Pool.<anonymous> (C:\Users\Daniel\OneDrive\Pega\COMMZGATE\trazability\api\node_modules\mongodb-core\lib\topologies\server.js:328:35),     at emitOne (events.js:96:13),     at Pool.emit (events.js:188:7),     at Connection.<anonymous> (C:\Users\Daniel\OneDrive\Pega\COMMZGATE\trazability\api\node_modules\mongodb-core\lib\connection\pool.js:280:12),     at Connection.g (events.js:292:16),     at emitTwo (events.js:106:13),     at Connection.emit (events.js:191:7),     at Socket.<anonymous> (C:\Users\Daniel\OneDrive\Pega\COMMZGATE\trazability\api\node_modules\mongodb-core\lib\connection\connection.js:187:10),     at Socket.g (events.js:292:16),     at emitNone (events.js:86:13),     at Socket.emit (events.js:185:7),     at Socket._onTimeout (net.js:342:8),     at ontimeout (timers.js:365:14),     at tryOnTimeout (timers.js:237:5),     at Timer.listOnTimeout (timers.js:207:5)]
Db.prototype.authenticate method will no longer be available in the next major release 3.x as MongoDB 3.6 will only allow auth against users in the admin db and will no longer allow multiple credentials on a socket. Please authenticate using MongoClient.connect with auth credentials.
Db.prototype.authenticate method will no longer be available in the next major release 3.x as MongoDB 3.6 will only allow auth against users in the admin db and will no longer allow multiple credentials on a socket. Please authenticate using MongoClient.connect with auth credentials.
Db.prototype.authenticate method will no longer be available in the next major release 3.x as MongoDB 3.6 will only allow auth against users in the admin db and will no longer allow multiple credentials on a socket. Please authenticate using MongoClient.connect with auth credentials.
[31merror[39m: uncaughtException: failed to connect to server [localhost:27017] on first connect [MongoError: connection 0 to localhost:27017 timed out] date=Sun Oct 29 2017 16:21:10 GMT-0300 (Hora verano Sudam√©rica Pac√≠fico), pid=5084, uid=null, gid=null, cwd=C:\Users\Daniel\OneDrive\Pega\COMMZGATE\trazability\api, execPath=C:\Program Files\nodejs\node.exe, version=v7.2.0, argv=[C:\Program Files\nodejs\node.exe, C:\Users\Daniel\OneDrive\Pega\COMMZGATE\trazability\api\index.js], rss=73232384, heapTotal=63512576, heapUsed=44648872, external=17981107, loadavg=[0, 0, 0], uptime=217.6810327, trace=[column=35, file=C:\Users\Daniel\OneDrive\Pega\COMMZGATE\trazability\api\node_modules\mongodb-core\lib\topologies\server.js, function=null, line=328, method=null, native=false, column=13, file=events.js, function=emitOne, line=96, method=null, native=false, column=7, file=events.js, function=Pool.emit, line=188, method=emit, native=false, column=12, file=C:\Users\Daniel\OneDrive\Pega\COMMZGATE\trazability\api\node_modules\mongodb-core\lib\connection\pool.js, function=null, line=280, method=null, native=false, column=16, file=events.js, function=Connection.g, line=292, method=g, native=false, column=13, file=events.js, function=emitTwo, line=106, method=null, native=false, column=7, file=events.js, function=Connection.emit, line=191, method=emit, native=false, column=10, file=C:\Users\Daniel\OneDrive\Pega\COMMZGATE\trazability\api\node_modules\mongodb-core\lib\connection\connection.js, function=null, line=187, method=null, native=false, column=16, file=events.js, function=Socket.g, line=292, method=g, native=false, column=13, file=events.js, function=emitNone, line=86, method=null, native=false, column=7, file=events.js, function=Socket.emit, line=185, method=emit, native=false, column=8, file=net.js, function=Socket._onTimeout, line=342, method=_onTimeout, native=false, column=14, file=timers.js, function=ontimeout, line=365, method=null, native=false, column=5, file=timers.js, function=tryOnTimeout, line=237, method=null, native=false, column=5, file=timers.js, function=Timer.listOnTimeout, line=207, method=listOnTimeout, native=false], stack=[MongoError: failed to connect to server [localhost:27017] on first connect [MongoError: connection 0 to localhost:27017 timed out],     at Pool.<anonymous> (C:\Users\Daniel\OneDrive\Pega\COMMZGATE\trazability\api\node_modules\mongodb-core\lib\topologies\server.js:328:35),     at emitOne (events.js:96:13),     at Pool.emit (events.js:188:7),     at Connection.<anonymous> (C:\Users\Daniel\OneDrive\Pega\COMMZGATE\trazability\api\node_modules\mongodb-core\lib\connection\pool.js:280:12),     at Connection.g (events.js:292:16),     at emitTwo (events.js:106:13),     at Connection.emit (events.js:191:7),     at Socket.<anonymous> (C:\Users\Daniel\OneDrive\Pega\COMMZGATE\trazability\api\node_modules\mongodb-core\lib\connection\connection.js:187:10),     at Socket.g (events.js:292:16),     at emitNone (events.js:86:13),     at Socket.emit (events.js:185:7),     at Socket._onTimeout (net.js:342:8),     at ontimeout (timers.js:365:14),     at tryOnTimeout (timers.js:237:5),     at Timer.listOnTimeout (timers.js:207:5)]
Db.prototype.authenticate method will no longer be available in the next major release 3.x as MongoDB 3.6 will only allow auth against users in the admin db and will no longer allow multiple credentials on a socket. Please authenticate using MongoClient.connect with auth credentials.
